name: Docker Build

on:
  workflow_call:

jobs:
 docker_build_job:
   runs-on: ubuntu-latest
   steps:
    - name: Check out code
      uses: actions/checkout@v4
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag frontend:$(date +%s)

    - name: Save Docker Image
      run: docker save frontend:latest -o image.tar

    - name: Upload image as artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: image.tar