name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:

  pytests:
    uses: alfierushby/github_actions/.github/workflows/pytests.yml@main

  sonarcloud-scan:
    uses: alfierushby/github_actions/.github/workflows/sonar_scan.yml@main
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}
  
  build-docker:
    uses: alfierushby/github_actions/.github/workflows/docker_build.yml@main

  trivy_scan:
    needs: 
      - build-docker
    uses: alfierushby/github_actions/.github/workflows/trivy_scan.yml@main

  push-to-ecr:
    needs: 
      - trivy_scan
      - pytests
      - sonarcloud-scan
    uses: alfierushby/github_actions/.github/workflows/ecr_push.yml@main
    secrets:
      account_id: ${{ secrets.ACCOUNT_ID }}
      role_name: ${{ secrets.ROLE_NAME }}
      ecr_repo: ${{ secrets.ECR_REPO }}
      ecr_alias: ${{ secrets.ECR_ALIAS }}



      