name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    uses: alfierushby/priorityqueue_frontend/.github/workflows/docker_build.yml@main