name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:

  build-docker:
    uses: alfierushby/priorityqueue_frontend/.github/workflows/docker_build.yml@main

  trivy_scan:
    needs: build-docker
    uses: alfierushby/priorityqueue_frontend/.github/workflows/trivy_scan.yml@main

  sonarcloud-scan:
    uses: alfierushby/priorityqueue_frontend/.github/workflows/sonar_scan.yml@main
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}

  push-to-ecr:
    needs: 
      - trivy_scan
      - sonarcloud-scan
    uses: alfierushby/priorityqueue_frontend/.github/workflows/ecr_push.yml@main
    with:
      account_id: "913524907347"
      role_name: "ECR"
      ecr_repo: "issue_creator/frontend"
      ecr_alias: "i8t8f9f7"