name: Trivy Scan

on:
  workflow_call:

jobs:
  trivy-scan:
      runs-on: ubuntu-latest
      steps:
        - name: Download Docker Artifact
          uses: actions/download-artifact@v4
          with:
            name: docker-image
            path: .

        - name: Load Docker Image
          run: docker load -i image.tar

        - name: Run Trivy vulnerability scan
          uses: aquasecurity/trivy-action@master
          with:
            image-ref: "image:latest"
            format: "table"
            exit-code: 1  # Fails the job if vulnerabilities are found
            severity: "CRITICAL,HIGH"